Public Enum SettingsIdentifier
    INIPATH
    PATH
    PLAYLISTPATH
    LOGPATH
    LYRPATH
    FTPPATH

    REMOTE
    PORT
    REMOTE_BLOCK_MESSAGES
    REMOTE_BLOCK_EXT_IPS

    GENRES

    FORM_LOCKED
    LOG_PATH_KEY
    PLAY_MODE
    VOLUME
    MUSIC_SOURCE
    AUTO_CLICKER
    CLICK_COUNTER_ENABLED
    CURSOR_MOVER
    CURSOR_MOVER_INCR
    CURSOR_MOVER_DELAY
    AUTO_CLICKER_FREQ
    AUTO_CLICKER_REP
    MACROS_ENABLED
    RADIO_SORT
    TRACK_SORT
    SEARCH_ALL_FOLDERS
    SEARCH_PARTS
    DARK_THEME
    SAVE_WIN_POS_SIZE
    WIN_SIZE
    WIN_POS
    WIN_MAX
    BALANCE
    PLAY_RATE
    RANDOM_NEXT_TRACK
    PLAYLIST_SAVE_HISTORY
    AUTOSTARTS

    KEYLOGGER
    KEYLOGGER_PATH
    KEYLOGGER_ALLOW_HOTKEYS
    KEYLOGGER_RECORD_WINDOW

    REMOVE_NEXT_TRACK
    DATE_LOG_START
    FONT_FOLDERS
    FONT_TRACKS
    FONT_LYRICS
    DELAY_MS
    FTP_IP
    FTP_USER
    FTP_PW
    FTP_AUTO_UPDATE
    FTP_PUBLISH
    LYRICS_AUTO_SAVE
    IGNORE_ERRORS
    EXCLUDED_FOLDERS

    TRACK_PARTS_AUTO_SAVE
    TRACK_PARTS_PLAY_ON_CHANGE
    TRACK_SELECTION_SEARCH_SOURCE
    TRACK_SELECTION_PLAY_ON_CLICK

    LAST_TRACK_FILE
    LAST_TRACK_DIR
    LAST_TRACK_RECORDED_TIME
    LAST_TRACK_APPLY_TIME

    PLAYLIST_HISTORY
    TRACKS_COUNT
    TRACKS_TIME
    RADIO_STATIONS
    RADIO_TIME
    GENRES_MAPPING
    HOTKEY_MAPPING
    CLICK_COUNTER
End Enum
